jupyterbook/content/ioos_installation_conda.md

@MathewBiddle do you mind taking a quick look at this one? I removed some old syntax and updated a few things.

minor updates to the install instructions

---

jupyterbook/content/code_gallery/data_access_notebooks/2016-10-12-fetching_data.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2016-11-15-glider_data_example.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2016-12-19-exploring_csw.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2016-12-20-searching_glider_deployments.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2016-12-22-boston_light_swim.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2017-01-18-siphon-explore-thredds.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2017-03-21-ERDDAP_IOOS_Sensor_Map.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2017-06-12-NCEI_RA_archive_history.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2017-07-25-HFRadar_currents.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2017-08-01-xtractoR.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2017-11-30-rerddap.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2017-12-15-finding_HFRadar_currents.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2018-03-01-erddapy.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2019-03-08-grids-temperature.ipynb
jupyterbook/content/code_gallery/data_access_notebooks/2021-10-19-multiple-erddap-search.ipynb
jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2016-11-16-CF-UGRID-SGRID-conventions.ipynb
jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2017-01-23-R-notebook.ipynb
jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2017-03-30-octave_notebook_example.ipynb
jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2018-03-15-ssh-skillscore.ipynb
jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2018-03-30-wave_height_assessment.ipynb
jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2018-12-04-grids.ipynb
jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2020-02-14-QARTOD_ioos_qc_Water-Level-Example.ipynb
jupyterbook/content/code_gallery/data_management_notebooks/2017-05-14-running_compliance_checker.ipynb
jupyterbook/content/code_gallery/data_management_notebooks/2017-11-01-Creating-Archives-Using-Bagit.ipynb
jupyterbook/content/code_gallery/data_management_notebooks/2018-02-27-pocean-timeSeries-demo.ipynb
jupyterbook/content/code_gallery/data_management_notebooks/2020-10-10-GTS.ipynb
jupyterbook/content/code_gallery/data_management_notebooks/2020-12-08-DataToDwC.ipynb

adding created date to all notebooks

---

jupyterbook/content/code_gallery/data_access_notebooks/2016-12-19-exploring_csw.ipynb
pytest.ini

This notebook no longer runs as expected b/c the data either changed or was removed. The code is still valid though and I added the stale warning at the top to let users know.

skip stale notebook

---

.github/workflows/deploy-docs.yml
.github/workflows/tests.yml

Updating the GitHub Action versions.

update GHA versions

---

jupyterbook/content/code_gallery/data_access_notebooks/2020-10-10-GTS.ipynb

Thank you for send a Pull Request to our code gallery! When adding or updating a notebook please check if:

closes #100

---

.github/dependabot.yml
.github/workflows/deploy-docs.yml
.github/workflows/test-env.yml
.github/workflows/test_data_access_notebooks.yml
.github/workflows/test_data_analysis_and_visualization_notebooks.yml
.github/workflows/test_data_management_notebooks.yml
.pre-commit-config.yaml

This should help us keep the GitHub Actions updated.

Dependabot

---

.binder/conda-lock.yml
.binder/environment-python_and_r.yml
.binder/environment.yml

xref.: https://github.com/ioos/ioos_code_lab/issues/132#issuecomment-1485683515

step one to fix 132

---

jupyterbook/content/ioos_installation_conda.md

Thanks @rsignell-usgs for reporting this.

fix download confusion

---

.binder/conda-lock.yml
.binder/environment-python_and_r.yml
.binder/environment.yml

I thought we had this one there but we didn't.

Add nbclassic to the env

---

.github/workflows/test-install-instructions.yml

Closes https://github.com/ioos/ioos_code_lab/issues/54
We don't really know what is going on in #54 so let's execute the same steps from our instructions in the CIs and catch possible errors.

test install instructions

---

CONTRIBUTING.md

added spelling fix as a demo for git

fixing contributing guidance

---

.pre-commit-config.yaml
jupyterbook/content/add_colab_install_missing_deps.py

We added the extra cell to run on colab but I never added the script used to modify all the notebooks. Adding it now in case we need to modify this in the future.

add colab missing dependencies script

---

.binder/conda-lock.yml
.binder/environment-python_and_r.yml
.binder/environment.yml

I'll add a notebook that uses this soon but right now I mostly want folks using the IOOS env as a kitchen sink to have it so then can run the metrics notebook.

add gliderpy

---

.binder/conda-lock.yml
.binder/environment-python_and_r.yml
.binder/environment.yml

add ioos metrics

---

jupyterbook/content/intro.md

@MathewBiddle this could be a link in that paragraph. The button seems out of place here. Do you have another idea where to put it?

Add contribute button

---

jupyterbook/_toc.yml
jupyterbook/content/contact_us.md

Remove contact_us page

---

.binder/conda-lock.yml
.binder/environment-python_and_r.yml
.binder/environment.yml

This will help @kbailey-noaa run the glider metrics.

add latest ioos_metrics

---

jupyterbook/_config.yml
pytest.ini

Let's wait to merge this when we have an update on the NCEI URL that is breaking the page build. See https://github.com/ioos/ioos_code_lab/pull/199#issuecomment-2115819168 for more context.

Skip all notebooks that uses the R kernel

---

jupyterbook/content/code_gallery/data_access_notebooks/2017-06-12-NCEI_RA_archive_history.ipynb

Fix CeNCOOS acronym mapping

---

jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2024-05-16-white_shark_water_temp.ipynb

xref.: https://github.com/ioos/ioos-atn-data/pull/83

fix broken link

---

.binder/conda-lock.yml
.binder/environment-python_and_r.yml
.binder/environment.yml

Add intake dask

---

jupyterbook/content/ioos_installation_conda.md

This one was reported to me earlier this week by a user. I glad people are still reading these!

Fix a minor typo

---

.pre-commit-config.yaml

Update pre-commits and fix new lints

---

.github/workflows/relock.yml

This should keep the lockfile updated and us informed of any breaking changes in the dependencies.

GitHub Actions to update the lockfile

---

jupyterbook/content/code_gallery/data_analysis_and_visualization_notebooks/2024-08-27-plotting-interface-gliderpy.ipynb

Forgot to hide the Google Colab start cell from the rendered notebook.

Hide Google Colab cell
